server:
  port: 9080

spring:
  datasource:
    #driver-class-name: org.postgresql.Driver
    #url: "jdbc:postgresql://localhost:5432/apiapplication"
    username: "dmly"
    password: "dmly"
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:apiapplication
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.H2Dialect